// Run in GitHub Actions with Playwright and Chromium's software WebGL renderer.
import {chromium} from 'playwright';
import {mkdir,copyFile} from 'node:fs/promises';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import {extname,join,normalize} from 'node:path';
const root=process.cwd();
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.webp':'image/webp','.jpg':'image/jpeg','.png':'image/png','.webmanifest':'application/manifest+json'};
const server=createServer(async(req,res)=>{try{const relative=normalize(decodeURIComponent(new URL(req.url,'http://localhost').pathname)).replace(/^\/+/, '')||'index.html';if(relative.startsWith('..'))throw Error('Bad path');const body=await readFile(join(root,relative));res.writeHead(200,{'Content-Type':types[extname(relative)]||'application/octet-stream'});res.end(body);}catch{res.writeHead(404);res.end('Not found');}});
await new Promise(resolve=>server.listen(8080,'127.0.0.1',resolve));await mkdir('media',{recursive:true});
const browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});
try{
 const desktop=await browser.newContext({viewport:{width:1440,height:900},deviceScaleFactor:1,recordVideo:{dir:'media',size:{width:1280,height:800}}});
 const page=await desktop.newPage();await page.goto('http://127.0.0.1:8080/#date=1969-07-20&body=earth');
 await page.locator('#loading').waitFor({state:'hidden',timeout:30000});
 if(await page.locator('#webgl-error').isVisible()||await page.locator('canvas').count()===0)throw Error('WebGL2 did not initialize; refusing to publish misleading captures');
 await page.locator('#support-close').click();
 await page.locator('#earth-shortcut').click();
 if(!await page.locator('#back-system').isVisible()||!await page.locator('#earth-places').isVisible())throw Error('Earth navigation is inaccessible');
 await page.locator('[data-lat="35"][data-lon="-95"]').click();
 await page.locator('#back-system').click();
 await page.locator('[data-age="4540000000"]').click();
 if(!page.url().includes('age=4540000000')||!((await page.locator('#era-status').innerText()).includes('illustrative')))throw Error('Deep-time endpoint or scope label is broken');
 await page.locator('#date-input').fill('0044-03-15 BCE');await page.locator('#date-input').press('Tab');
 if(!page.url().includes('date=0044-03-15-BCE'))throw Error('BCE date is not shareable');
 await page.locator('#date-input').fill('10000-12-31 CE');await page.locator('#date-input').press('Tab');
 if(!page.url().includes('date=10000-12-31-CE'))throw Error('Calendar endpoint is broken');
 await page.locator('#date-input').fill('1969-07-20 CE');await page.locator('#date-input').press('Tab');
 await page.waitForTimeout(1000);await page.screenshot({path:'media/desktop.png'});
 await page.locator('#focus-body').click();await page.waitForTimeout(1100);
 await page.locator('#overview').click();await page.waitForTimeout(1100);
 await page.locator('#body-list [data-body="earth"]').click();await page.locator('#earth-surface').click();await page.waitForTimeout(1100);
 if(await page.locator('#body-list [data-body="moon"]').count()!==0)throw Error('Moon should start hidden');
 await page.locator('#moon-toggle').check();await page.locator('#body-list [data-body="moon"]').click();
 if(!page.url().includes('body=moon'))throw Error('Moon selection is not shareable');
 await page.locator('#moon-toggle').uncheck();
 if(await page.locator('#body-list [data-body="moon"]').count()!==0||page.url().includes('body=moon'))throw Error('Moon toggle did not hide the Moon');
 await page.locator('#play').click();await page.waitForTimeout(1600);await page.locator('#play').click();
 const video=await page.video().path();await desktop.close();await copyFile(video,'media/demo.webm');
 const mobile=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});
 const small=await mobile.newPage();await small.goto('http://127.0.0.1:8080/#date=1989-08-25&body=neptune');await small.locator('#loading').waitFor({state:'hidden',timeout:30000});
 if(await small.locator('#webgl-error').isVisible()||await small.locator('canvas').count()===0)throw Error('Mobile WebGL2 did not initialize');
 await small.locator('#support-close').click();
 await small.locator('#earth-shortcut').click();
 if(!await small.locator('#earth-places').isVisible())throw Error('Earth regions are inaccessible on mobile');
 if(await small.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile layout overflows viewport');
 await small.locator('#body-list [data-body="moon"]').count().then(count=>{if(count)throw Error('Moon should also start hidden on mobile');});await mobile.close();
}finally{await browser.close();server.close();}
